### ISSUE TITLE
Include cutoff where value of the threshold that the cumulative group sum must cross.

### ISSUE THREAD

**Issue by shahronak47** [ekstroem/MESS#4]
Currently, `cumsumbinning` function does **not** cross the `cutoff` value. So it takes cumulative sum until `cutoff` or less than it.

```
x <- c(3, 4, 5, 12, 1, 5, 3)
MESS::cumsumbinning(x, 10)
#[1] 1 1 2 3 4 4 4
```

Is it possible to include behaviour where `cutoff` is the value where the cumulative group sum **is** crossed. So the output for above is

```
#[1] 1 1 1 2 3 3 3
```

**Comment by ekstroem** [comment]
That makes sense. Try the version I just uploaded, and use the argument `cutwhenpassed`. (If you have any suggestions for a better name for the argument then please let me know)

    cumsumbinning(x, threshold=10, cutwhenpassed=TRUE)

Also, I might rename to function to `bin_cumsum` at one point.

**Comment by ekstroem** [comment]
Reopening until it's been checked that it works

**Comment by shahronak47** [comment]
Thanks @ekstroem for an immediate fix. I always have problem installing packages from github. If you have tested this and think it solves the issue, you can close it.

**Comment by ekstroem** [comment]
Is 

    devtools::install_github("ekstroem/MESS")

not working? In any case it will be a wee bit of time before I submit an update to CRAN.

**Comment by shahronak47** [comment]
just checked this. Works as expected. Thank you @ekstroem

**Comment by ekstroem** [comment]
Perfect!
