### ISSUE TITLE
power_t_test function typo

### ISSUE THREAD

**Issue by shunranw** [ekstroem/MESS#7]
Looks like there's a small typo in the power_t_test function, at MESS/R/power.t.test line 63: if (!is.null(sd.ratio) && sd.ratio < 0)
      stop("sd.ratio between group sd's cannot be less than 1"). Looks like it should be sd.ratio < 1 instead of 0.

**Comment by ekstroem** [comment]
Thanks! Nicely spotted. Should be fixed in the update I just pushed up
