### ISSUE TITLE
power_prop_test cannot handle solving for low power 

### ISSUE THREAD

**Issue by katherineking4** [ekstroem/MESS#8]
There seems to be an issue when solving for power in the power_prop_test when the resulting power will be low (less than .6). Here is an example of the error along with the output from power.prop.test.

p1<-.8
p2<-.75
n<- 60
alpha <-.05#default

power_prop_test(n = n, 
                     p1 = p1, 
                     p2 = p2, 
                     ratio = 1,
                     sig.level = alpha,
                     power = NULL,
                     alternative = "two.sided")
#Error in uniroot(function(power) eval(p.body) - n, c(1e-05, 0.99999),  : 
#did not succeed extending the interval endpoints for f(lower) * f(upper) <= 0
#In addition: Warning message:
#In qnorm(1 - power) : NaNs produced

power.prop.test(n = n, 
                     p1 = p1, 
                     p2 = p2, 
                     sig.level = alpha,
                     power = NULL,
                     alternative = "two.sided")

#Two-sample comparison of proportions power calculation 
#n = 60
#p1 = 0.8
#p2 = 0.75
#sig.level = 0.05
#power = 0.09569441
#alternative = two.sided
#NOTE: n is number in *each* group

**Comment by ekstroem** [comment]
Yeah. That is an issue with the normal approximation to the binomial when the power (and thus the sample size) is low. Will try to update the code to have a better numerical solution.

**Comment by ekstroem** [comment]
I've pushed a new version that hopefully is more stable for low power calculations so the approximations will not mess the computations up. Please take it out for a spin!

**Comment by katherineking4** [comment]
It looks good :) I no longer get an error when computing low power. Thanks for your quick help!
